name: mic_rwkv
channels:
  - pytorch
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - numpy=1.23.4
  - pandas=1.4.3
  - python=3.9.13
  - pytorch=1.12.1
  - yaml=0.2.5
  - pip:
    - ninja==1.11.1
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - tqdm==4.64.1
